# Generated by Django 3.0.8 on 2020-07-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=150)),
                ('professor', models.CharField(max_length=50)),
                ('instruction_id', models.CharField(max_length=100)),
                ('rq_year', models.CharField(max_length=150)),
                ('rq_semester', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('credit', models.CharField(max_length=100)),
                ('class_time', models.CharField(max_length=100)),
                ('required', models.BooleanField()),
                ('foreigner', models.BooleanField()),
                ('team_teaching', models.BooleanField()),
                ('mooc', models.BooleanField()),
                ('online', models.BooleanField()),
                ('number_of_people', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
